{% set versions = {
    "2.2.1": "74912371e952bffb586a92c17983dc2decb5f41f"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "xfitter")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  git_url: "https://gitlab.cern.ch/fitters/xfitter"
  git_rev: {{ versions.get(version, "HEAD") }}
  patches:
    - patches/conda.patch

requirements:
  build:
    - {{ compiler('gfortran') }}
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

    - cmake<4
    - make
    - rsync

  host:
    - xfitter-dev

  run:
    - xfitter-dev

test:
  commands:
    - cd examples && xfitter defaultNLO
    - cd examples && xfitter ZEUSjets2023

about:
  home: "https://gitlab.cern.ch/fitters/xfitter"
  license: "GPL-3.0"
  summary: "xFitter - A PDF fit program from HERA."
  description: |
    xFitter is an open source QCD fit framework desinged to extract PDFs and assess the impact of new data.
    The xFitter project is is a common initiative by the H1 and ZEUS collaborations and extended to the LHC collaborations to provide precision QCD analyses.

extra:
  recipe-maintainers:
    - meiyasan
